all: enigma

enigma: colaDobleCaracteresFun.c PA1-07_encri.c
	clear
	gcc -Wall -c colaDobleCaracteresFun.c
	gcc -Wall -g -o PA1-07 PA1-07_encri.c colaDobleCaracteresFun.o

play: PA1-07
	clear
	./PA1-07

delet:
	clear
	rm *.o
	rm PA1-07

